spring:
    application:
            name: eve
    profiles:
        # The commented value for `active` can be replaced with valid spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active:
    datasource:
      url: jdbc:mysql://localhost:3306/eve?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true
      username: root
      password:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name:  com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
#    boot:
#      admin:
#        url:
#          http://localhost:8080
#info:
#    build:
#        artifact: dayan
#        name: eve
#        description: eve spring boot
#        version: 1.0.0
#jackson:
#  serialization:
#    indent_output: true
#endpoints:
#  health:
#    sensitive: false
#management:
#  security:
#    enabled: false
# todo 在线上配置
#    redis:
##      database: 0
#      host: localhost
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#        max-wait: -1
#      port: 6379
#      timeout: 0
server:
    port: 8080
    session:
        timeout: 5184000 #60天
    apiContext: api
    versionContext: v
    context-path: /

mybatis:
    config-location: classpath:config/mybatis-config.xml
    mapperLocations: classpath*:dayan.eve.repository/*.xml,classpath*:dayan.eve.repository/*/*.xml
    typeAliasesPackage: dayan.eve.model
eve:
  testApiPrefix: http://inc.dareyan.cn:8881
  localPrefix: d:/usr/tomcat-8881-monitor/webapps
  moApiPrefix: http://mo.microyan.com
  walleApiPrefix: http://zs.microyan.com
  mo:
     username: dykj
     password: hzdykj709
     tokenUrl: ${eve.moApiPrefix}/api/token
     schoolMajor: ${eve.moApiPrefix}/api/school/major/
     schoolList: ${eve.moApiPrefix}/api/school/list
     schoolPlan: ${eve.moApiPrefix}/api/school/sum_plan
     schoolSumPlan: ${eve.moApiPrefix}/api/school/sumPlan
     schoolDetail: ${eve.moApiPrefix}/api/school/
     schoolNames: ${eve.moApiPrefix}/api/school/names/
     schoolScore: ${eve.moApiPrefix}/api/score/school
     majorDetail: ${eve.moApiPrefix}/api/major/
     majorList: ${eve.moApiPrefix}/api/major/list
     holQuestion : ${eve.moApiPrefix}/api/hol/question
     holPersonality : ${eve.moApiPrefix}/api/hol/personality
     holJobClass : ${eve.moApiPrefix}/api/hol/jobClass
     holMajorType : ${eve.moApiPrefix}/api/hol/majorType
     holMajors : ${eve.moApiPrefix}/api/hol/majors
  clock:
    inStart: 04:00:00
    inEnd: 07:59:59
    outStart: 21:00:00
    outend: 23:59:59
    clockedContent: 本时间段已打卡
    unclockedContent: 用力打卡！！
    morningClockedContent: 早上4:00-8:00记得来打卡哟
    eveningClockedContent: 晚上21:00-24:00记得来打卡哟
    dayStart:
  walle:
    username: eve
    password: hzdykj709
    clientId: walle-client
    grantType: password
    refreshGrantType: refresh_token
    csTopHashId: V4lgnzyjY
    evePlatformId: 861
    qaAnswer: ${eve.walleApiPrefix}/api/qa/getAnswer?access_token=%s
    qaHint: ${eve.walleApiPrefix}/api/eve/inputHint?access_token=%s
    qaGreet: ${eve.walleApiPrefix}/api/eve/greeting?access_token=%s&platformId=%s
    qaFreq: ${eve.walleApiPrefix}/api/qa/getFreq.jsonp
    csAsk: ${eve.walleApiPrefix}/api/qa/askCS.jsonp
    csClose: ${eve.walleApiPrefix}/api/qa/closeCustomService.jsonp
    csStaff: ${eve.walleApiPrefix}/api/eve/cs/csStaff?access_token=%s&platformId=%s
    csAllOnline: ${eve.walleApiPrefix}/api/eve/cs/allOnline
    platform: ${eve.walleApiPrefix}/api/eve/platform?access_token=%s
    url: ${eve.walleApiPrefix}/
    loginUrl: ${eve.walleApiPrefix}/api/eve/login
    statisUrl: ${eve.walleApiPrefix}/api/statis
    guestbookSendQuestion: ${eve.walleApiPrefix}/api/guestbook/appsubmit
    guestbookGetschool: ${eve.walleApiPrefix}/api/guestbook/getschool
    guestbookPut: ${eve.walleApiPrefix}/api/eve/guestbook
    guestbookGet: ${eve.walleApiPrefix}/api/eve/guestbook/school
    messageHandlerSend: ${eve.walleApiPrefix}/api/messagehandler/send
    answer: ${eve.walleApiPrefix}/api/eve/answer
    freq :  ${eve.walleApiPrefix}/api/eve/freqQuestion?access_token=%s
    hot: ${eve.walleApiPrefix}/api/eve/hotQuestion?access_token=%s
    visitor: ${eve.walleApiPrefix}/api/eve/visitor
    feedback: ${eve.walleApiPrefix}/api/eve/feedback?access_token=%s
    accessToken: ${eve.walleApiPrefix}/oauth/token
    csOnlineDisplayNum : 4
    csOnlineCacheSeconds: 3600000
    hotQuestionNum : 30
    freqQuestionNum: 5
  school:
    logoPrefix: ${eve.moApiPrefix}/open/school/badge/
    imageUrlPrefix: ${eve.testApiPrefix}/image/schoolimage/
    searchPromptNum: 20
  image:
    accountPortraitReadUrlPrefix: ${eve.testApiPrefix}/image/account/portrait/
    accountPortraitCreateUrlPrefix: ${eve.localPrefix}/image/account/portrait/
    informationReadUrlPrefix: ${eve.testApiPrefix}/image/information/
    informationCreateUrlPrefix: ${eve.localPrefix}/image/information/
    bannerReadUrlPrefix: ${eve.testApiPrefix}/image/banner/
    bannerCreateUrlPrefix: ${eve.localPrefix}/image/banner/
    adsReadUrlPrefix: ${eve.testApiPrefix}/image/ads/
    adsCreateUrlPrefix: ${eve.localPrefix}/image/ads/
  html:
    informationReadUrlPrefix: ${eve.testApiPrefix}/image/information/html/
    informationCreateUrlPrefix: ${eve.localPrefix}/image/information/html/
  course:
    detail: ${eve.testApiPrefix}/eve/app/course/detail
    result :  ${eve.testApiPrefix}/eve/app/course/result
  alipay:
    notifyUrlPrefix :  http://112.16.81.39/eve/api/v20/mobile/course/buy
  swagger:
      title: Eve API For Frontend Engineer
      description: Eve API documentation
      version: 0.0.1
      termsOfServiceUrl:
      contactName:
      contactUrl:
      contactEmail:
      license:
      licenseUrl:

  topic:
    topicReadUrlPrefix: ${eve.testApiPrefix}/image/topic/
    topicCreateUrlPrefix: ${eve.localPrefix}/image/topic/
    replyExp: 5
    createExp: 10
    beLikedExp: 2
    beRepliedxp: 2
    maxContentSize: 1024
    likeNotificationMsg: 给你点了个赞
    noticeTitle: 您的帖子已有回复
    messageTemplate: 您的帖子：[%s]已有回复，快去查看吧！
  async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

#\u6d4b\u8bd5
#walle.cs.top.hashid = DKowlnrK8