spring:
  profiles:
    active: dev
#eve:
#  walle:
#    qaAnswer: http://inc.dareyan.cn:8081/walle2/api/qa/getAnswer
#    qaHint: http://inc.dareyan.cn:8081/walle2/api/eve/inputHint
#    qaGreet: http://inc.dareyan.cn:8081/walle2/api/eve/greeting
#    qaFreq: http://inc.dareyan.cn:8081/walle2/api/qa/getFreq.jsonp
#    csAsk: http://inc.dareyan.cn:8081/walle2/api/qa/askCS.jsonp
#    csClose: http://inc.dareyan.cn:8081/walle2/api/qa/closeCustomService.jsonp
#    csStaff: http://inc.dareyan.cn:8081/walle2/api/eve/cs/csStaff
#    csAllOnline: http://inc.dareyan.cn:8081/walle2/api/eve/cs/allOnline
#    evePlatformId: 861
#    platform: http://inc.dareyan.cn:8081/walle2/api/eve/platform
#    url: http://inc.dareyan.cn:8081/walle2/
#    loginUrl: http://inc.dareyan.cn:8081/walle2/api/eve/login
#    statisUrl: http://inc.dareyan.cn:8081/walle2/api/statis
#    guestbookSendQuestion: http://inc.dareyan.cn:8081/walle2/api/guestbook/appsubmit
#    guestbookGetschool: http://inc.dareyan.cn:8081/walle2/api/guestbook/getschool
#    guestbookPut: http://inc.dareyan.cn:8081/walle2/api/eve/guestbook
#    guestbookGet: http://inc.dareyan.cn:8081/walle2/api/eve/guestbook/school
#    messageHandlerSend: http://inc.dareyan.cn:8081/walle2/api/messagehandler/send
#    answer: http://inc.dareyan.cn:8081/walle2/api/eve/answer
#    freq :  http://inc.dareyan.cn:8081/walle2/api/eve/freqQuestion
#    hot: http://inc.dareyan.cn:8081/walle2/api/eve/hotQuestion
#    visitor: http://inc.dareyan.cn:8081/walle2/api/eve/visitor
#    feedback: http://inc.dareyan.cn:8081/walle2/api/eve/feedback
#    accessToken: http://inc.dareyan.cn:8081/walle2/oauth/token
#  school:
#    logoPrefix: http://mo.microyan.com/open/school/badge/
#    imageUrlPrefix: http://192.168.200.55:8881/image/schoolimage/
#  image:
#    topicReadUrlPrefix: http://192.168.200.55:8881/image/topic/
#    topicCreateUrlPrefix: d:/usr/tomcat-8881-monitor/webapps/image/topic/
#    accountPortraitReadUrlPrefix: http://192.168.200.55:8881/image/account/portrait/
#    accountPortraitCreateUrlPrefix: d:/usr/tomcat-8881-monitor/webapps/image/account/portrait/
#    informationReadUrlPrefix: http://192.168.200.55:8881/image/information/
#    informationCreateUrlPrefix: d:/usr/tomcat-8881-monitor/webapps/image/information/
#    bannerReadUrlPrefix: http://192.168.200.55:8881/image/banner/
#    bannerCreateUrlPrefix: d:/usr/tomcat-8881-monitor/webapps/image/banner/
#    adsReadUrlPrefix: http://192.168.200.55:8881/image/ads/
#    adsCreateUrlPrefix: d:/usr/tomcat-8881-monitor/webapps/image/ads/
#  html:
#    informationReadUrlPrefix: http://192.168.200.55:8881/image/information/html/
#    informationCreateUrlPrefix: d:/usr/tomcat-8881-monitor/webapps/image/information/html/
#  course:
#    detail :  http://192.168.200.55:8881/eve/app/course/detail
#    result :  http://192.168.200.55:8881/eve/app/course/result
#  alipay:
#    notifyUrlPrefix :  http://112.16.81.39/eve/api/v20/mobile/course/buy