spring:
    application:
            name: eve
    profiles:
        # The commented value for `active` can be replaced with valid spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active:
    datasource:
      url: jdbc:mysql://localhost:3306/eve?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true
      username: root
      password:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name:  com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
# todo 在线上配置
#    redis:
##      database: 0
#      host: localhost
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#        max-wait: -1
#      port: 6379
#      timeout: 0
server:
    port: 8080
    session:
        timeout: 5184000 #60天
    apiContext: api
    versionContext: v
    context-path: /

mybatis:
    config-location: classpath:config/mybatis-config.xml
    mapperLocations: classpath*:dayan.eve.repository/*.xml,classpath*:dayan.eve.repository/*/*.xml
    typeAliasesPackage: dayan.eve.model
eve:
  mo:
     username: dykj
     password: hzdykj709
     tokenUrl: http://mo.microyan.com/api/token
     schoolMajor: http://mo.microyan.com/api/school/major/
     schoolList: http://mo.microyan.com/api/school/list
     schoolPlan: http://mo.microyan.com/api/school/sum_plan
     schoolSumPlan: http://mo.microyan.com/api/school/sumPlan
     schoolDetail: http://mo.microyan.com/api/school/
     schoolNames: http://mo.microyan.com/api/school/names/
     schoolScore: http://mo.microyan.com/api/score/school
     majorDetail: http://mo.microyan.com/api/major/
     majorList: http://mo.microyan.com/api/major/list
     holQuestion : http://mo.microyan.com/api/hol/question
     holPersonality : http://mo.microyan.com/api/hol/personality
     holJobClass : http://mo.microyan.com/api/hol/jobClass
     holMajorType : http://mo.microyan.com/api/hol/majorType
     holMajors : http://mo.microyan.com/api/hol/majors
  clock:
    inStart: 04:00:00
    inEnd: 07:59:59
    outStart: 21:00:00
    outend: 23:59:59
    clockedContent: 本时间段已打卡
    unclockedContent: 用力打卡！！
    morningClockedContent: 早上4:00-8:00记得来打卡哟
    eveningClockedContent: 晚上21:00-24:00记得来打卡哟
    dayStart:
  walle:
    username: eve
    password: hzdykj709
    clientId: walle-client
    grantType: password
    refreshGrantType: refresh_token
    csTopHashId: V4lgnzyjY
    qaAnswer: http://zs.microyan.com/api/qa/getAnswer?access_token=%s
    qaHint: http://zs.microyan.com/api/eve/inputHint?access_token=%s
    qaGreet: http://zs.microyan.com/api/eve/greeting?access_token=%s&platformId=%s
    qaFreq: http://zs.microyan.com/api/qa/getFreq.jsonp
    csAsk: http://zs.microyan.com/api/qa/askCS.jsonp
    csClose: http://zs.microyan.com/api/qa/closeCustomService.jsonp
    csStaff: http://zs.microyan.com/api/eve/cs/csStaff?access_token=%s&platformId=%s
    csAllOnline: http://zs.microyan.com/api/eve/cs/allOnline
    evePlatformId: 861
    platform: http://zs.microyan.com/api/eve/platform?access_token=%s
    url: http://zs.microyan.com/
    loginUrl: http://zs.microyan.com/api/eve/login
    statisUrl: http://zs.microyan.com/api/statis
    guestbookSendQuestion: http://zs.microyan.com/api/guestbook/appsubmit
    guestbookGetschool: http://zs.microyan.com/api/guestbook/getschool
    guestbookPut: http://zs.microyan.com/api/eve/guestbook
    guestbookGet: http://zs.microyan.com/api/eve/guestbook/school
    messageHandlerSend: http://zs.microyan.com/api/messagehandler/send
    answer: http://zs.microyan.com/api/eve/answer
    freq :  http://zs.microyan.com/api/eve/freqQuestion?access_token=%s
    hot: http://zs.microyan.com/api/eve/hotQuestion?access_token=%s
    visitor: http://zs.microyan.com/api/eve/visitor
    feedback: http://zs.microyan.com/api/eve/feedback?access_token=%s
    accessToken: http://zs.microyan.com/oauth/token
    csOnlineDisplayNum : 4
    csOnlineCacheSeconds: 3600000
    hotQuestionNum : 30
    freqQuestionNum: 5
  school:
    logoPrefix: http://mo.microyan.com/open/school/badge/
    imageUrlPrefix: http://inc.dareyan.cn:8881/image/schoolimage/
    searchPromptNum: 20
  image:
    accountPortraitReadUrlPrefix: http://inc.dareyan.cn:8881/image/account/portrait/
    accountPortraitCreateUrlPrefix: d:/usr/tomcat-8881-monitor/webapps/image/account/portrait/
    informationReadUrlPrefix: http://inc.dareyan.cn:8881/image/information/
    informationCreateUrlPrefix: d:/usr/tomcat-8881-monitor/webapps/image/information/
    bannerReadUrlPrefix: http://inc.dareyan.cn:8881/image/banner/
    bannerCreateUrlPrefix: d:/usr/tomcat-8881-monitor/webapps/image/banner/
    adsReadUrlPrefix: http://inc.dareyan.cn:8881/image/ads/
    adsCreateUrlPrefix: d:/usr/tomcat-8881-monitor/webapps/image/ads/
  html:
    informationReadUrlPrefix: http://inc.dareyan.cn:8881/image/information/html/
    informationCreateUrlPrefix: d:/usr/tomcat-8881-monitor/webapps/image/information/html/
  course:
    detail: http://inc.dareyan.cn:8881/eve/app/course/detail
    result :  http://inc.dareyan.cn:8881/eve/app/course/result
  alipay:
    notifyUrlPrefix :  http://112.16.81.39/eve/api/v20/mobile/course/buy
  swagger:
      title: Eve API For Frontend Engineer
      description: Eve API documentation
      version: 0.0.1
      termsOfServiceUrl:
      contactName:
      contactUrl:
      contactEmail:
      license:
      licenseUrl:

  topic:
    topicReadUrlPrefix: http://inc.dareyan.cn:8881/image/topic/
    topicCreateUrlPrefix: d:/usr/tomcat-8881-monitor/webapps/image/topic/
    replyExp: 5
    createExp: 10
    likeExp: 2
    maxContentSize: 1024
    likeNotificationMsg: 给你点了个赞
  async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

#\u6d4b\u8bd5
#walle.cs.top.hashid = DKowlnrK8